### PR TITLE
Transmoogrification - Moose => Moo conversion of HTTP::Throwable

### PR DESCRIPTION
**Pull request by felliott**
Hello Ricardo,

This patchset switches HTTP::Throwable from Moose to Moo-based.  It passes all of the current tests, and I've also tested it with the Moose-based subclassing in timbunce/WebAPI-DBIC.  I've added dependecies on Type::Tiny, Types::Standard, Package::Variant, and namespace::clean.  Please let me know if there's anything you would like me to change or fix.  Thank you and have a great day!

Cheers,
Fitz

### CODE REVIEW

**Comment by rjbs** [comment]
I will test this against my work code base uses of HTTP-Throwable and either release or review by next week.  (It's on my calendar now!)

**Comment by rjbs** [comment]
I have tested my code against this, and it looks okay.

All of the roles had `use Moose::Role` replaced with `use Moo::Role`, which seem good, but then they had `no Moo::Role` replaced with … nothing.  So the classes end up with `with` methods, etc.

I will fix this locally, but please keep that in mind next time you do a transmoogrification like this.

**Comment by rjbs** [comment]
I have uploaded HTTP-Throwable-0.021-TRIAL.tar.gz.  I'll give this a while before making it the stable version.

**Comment by karenetheridge** [comment]
FWIW, I catch this in my dzil author bundle by including `[Test::CleanNamespaces]`.

**Comment by rjbs** [comment]
This has been released as v0.022.  Thank you for all your efforts!

**Pull request closed without merging**
