### PR TITLE
create a lookup registry for status code to ident

### PR DESCRIPTION
**Pull request by perigrin**
It would be nice if we had an easy way to convert status codes into
idents. This provides a method in `HTTP::Throwable::Factory` for doing
such a lookup.

### CODE REVIEW

**Comment by rjbs** [comment]
I've merged this locally, but I think I'd prefer this as `roles_for_status_code`.  Then `class_for` could treat `/\A[0-9]{3}\z/` as a status code, and you can `->throw(500)`.  Any objections or other thoughts?

**Comment by perigrin** [comment]
I think that would be awesome. I needed the lookup so I could use HTTP::Throwable on the _client_ side so being able to just do `->throw($res->code)` would certainly work for my needs.

**Comment by perigrin** [comment]
For posterity sake https://metacpan.org/source/PERIGRIN/HTTP-Thin-UserAgent-0.015/lib/HTTP/Thin/UserAgent.pm#L151 is how I'm using this feature currently (this PR is a port of that feature upstream)

**Comment by rjbs** [comment]
We discussed this on IRC and came to a conclusion that this would work well for both of us.  I added docs and tests, and it is released!

**Pull request closed without merging**
